### ISSUE TITLE
[BUG] Repository not found with current directory

### ISSUE THREAD

**Issue by orhun** [spenserblack/repofetch#181]
### What is the bug?

```
Error: Repository not found

Caused by:
    Non-GitHub remotes not yet supported
```

### Where is the bug?

To reproduce:

```sh
#!/usr/bin/env bash

cd $(mktemp -d)
git clone https://github.com/spenserblack/repofetch
cd repofetch
cargo run -- -r .
```

### Expected behavior
Successful run.

### What version?
Compiled from master + #180 

### What else is bugging you?
\-

**Comment by spenserblack** [comment]
Thanks for finding this! The issue is with this regex: https://github.com/spenserblack/repofetch/blob/d87c577bc1987f0a7bb7434dfeb5a5ac444d9584/src/main.rs#L19

It expects `.git` to be at the end of the remote URL, but as your reproduction shows, the `.git` suffix should be optional.
