### ISSUE TITLE
[NEW FEATURE] NetBSD package

### ISSUE THREAD

**Issue by 0323pin** [spenserblack/repofetch#184]
FYI, I've packaged `repofetch` for NetBSD and have merged the package into the main repo, https://mail-index.netbsd.org/pkgsrc-changes/2022/10/09/msg261795.html

Regards

**Comment by spenserblack** [comment]
Thanks for this! I'm not familiar with NetBSD, but from some quick skimming this means that repofetch is now installable with `pkgin`, right? Would you like to make a PR to update the installation docs?

**Comment by 0323pin** [comment]
Yes, I can make a PR and add it to the README.md.
Yes, you can install it with `pkgin` depending on which branch you are tracking. On current/development branch it should be available as a pre-compiled binary already tomorrow or the day after. The stable branch is released every three months, so there it should become available soon after Christmas.

I run the bleeding edge branch myself.

**Comment by spenserblack** [comment]
Hey, just an FYI that [I'm considering changing the implementing language](https://github.com/spenserblack/repofetch/issues/186#issue-1404594032). I haven't made any decision yet, but I'm assuming that if I did so it would severely affect the NetBSD package, wouldn't it?

**Comment by 0323pin** [comment]
@spenserblack Thanks for the heads-up. It really depends on what the changes look like. And, it's your app/work so, you decide.

If you move to python, js or, ruby I would ask if someone else is willing to take over as a package maintainer. I don't know anything about packaging stuff on those languages.
My packaging experience is limited to rust, c++, c and go.

**Comment by spenserblack** [comment]
@allcontributors please add @0323pin for platform

**Comment by 0323pin** [comment]
@spenserblack Thanks, I'm honoured.
