### ISSUE TITLE
Switch to a plugin-based implementation

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/repofetch#186]
repofetch will be rewritten to use plugins, including support for 3rd-party plugins, to render stats. Plugins will provide functions to detect if they should be used, methods for ASCII and stat lists, and register themselves to repofetch. The user will use a config file to specify which plugins should get loaded, and the user also has the opportunity to specify the plugin in the command line, useful if the correct plugin cannot be detected (e.g. `repofetch` is not run in a repo).

The justification is that there are plenty of git clients out there with different APIs, and it may not be desirable to officially support them all. Instead of making users wait while contributors/maintainers learn these APIs, it would be better to empower the user to be able to create their own plugins.

While the focus is still on repository stats (specifically the stats from client APIs), a plugin-based implementation also opens the door for *any* type of "-fetch" tool to be implemented as a plugin (a project rename may eventually be necessary :wink:)

******

# Old Notes

While the original intent was to support Bitbucket, GitLab, *and* GitHub, perhaps this project should focus purely on GitHub. There has been no work on setting up hosts besides GitHub, and an assumption that GitHub is being used allows more focus.

Perhaps this project should be more plugin-based -- the majority of GitHub logic is already in its own `mod`, maybe it should become a separate `repofetch-github` crate. That way different hosts can be authored easily.

The main `repofetch` crate can have selectively compiled dependencies and `register_foo` function calls. Each plugin could perhaps be a struct that implements a shared trait (need to avoid circular dependencies, `repofetch-impl` crate)?

******

# Notes

- If a plugin style is used, perhaps this should be rewritten in a language that can dynamically import packages, like Python, JS/TS, or Ruby.
- Args can be in the format `--plugin-<plugin name>-<option>` which would then get passed to the relevant plugin. Should they receive the full `--plugin-<plugin name>-<option>`, or `--<option>`? How will they register their options? Should this format be strictly enforced, or just recommended to avoid conflicts? Or should args be avoided altogether in favor of config file options?
- How does a user choose which plugin to use (and exclude others)? `--kebab-case-plugin-name`? Or maybe just make it `--PluginName`? Would following args then go to the initializer/constructor?

### TypeScript notes

Notes if implemented in typescript:

- If TS, this can be installed as a dev dependency to access type definitions.
- Plugins can export a `matchRemote` that returns the results of `''.match`
  - If multiple plugins match, detect this as a conflict (error? warning?)
- Plugins export a function `makeStats` that takes the match value as a parameter
- [Requiring global dependencies can be a pain](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders)
  - My global modules are in `$PREFIX/lib/node_modules`, but it looks like that's not loaded

### Ruby

- Global installs are easily required (and are the default)
- Plugins can be installed and required globally
- They can create instances of `Repofetch::Plugin` and register them with `Repofetch.register_plugin`
  - Will this be an issue with circular dependencies?
- Not as popular as JS or Python AFAIK
- Plugins are registered by adding their *require path* to the config file. The recommended require
  path is `'repofetch/foo'` (or `'repofetch/plugin/foo'`?)
- Hacktoberfest support could be a separate plugin, `repofetch/github-hacktoberfest`, which extends the base GitHub plugin
- View [this gist](https://gist.github.com/sue445/d840d6f68771a14a48fc) for an example of using temp
  directories in tests (useful for the tests involving git repositories)
- Options for plugins could possibly be `"--#{Plugin.name}"`. With optparse, `--root-option -- --argv` works.
- Best way to handle ASCII would probably be something like this: `'%{red}ooooo' % {red: RED}`
  - [rainbow](https://github.com/sickill/rainbow) can be used if needed
  - perhaps colors could come from a method that returns `{red: Red}` etc., but can be overridden to support other usage (e.g. if a Plugin should use true colors)
- Secrets (like `GITHUB_TOKEN`) could possibly live in a file like `$HOME/repofetch.env`/`$HOME/.repofetch.env` and be read with [dotenv](https://rubygems.org/gems/dotenv)
- [octokit](https://rubygems.org/gems/octokit) for the GitHub plugin

### Python

- Fairly popular language
- Can be dynamically imported
- global installs are the default unless using a venv

**Comment by spenserblack** [comment]
(moving conversation here since it can be annoying to converse in a closed issue)
In response to https://github.com/spenserblack/repofetch/issues/184#issuecomment-1290559046

@0323pin I'm curious what the biggest hurdles will be to packaging in a different language. Depending on the main issues, I can make design choices that make this easier to package.

**Comment by 0323pin** [comment]
@spenserblack I'm sure, I'd eventually figure it out, don't worry.
It's not so much the language _per se_, it's more how things need to be handled on our side.

Have you decided on what language you are going to use?

Funny enough, I've updated [onefetch](https://github.com/o2sh/onefetch) this week and thought about this.

**Comment by spenserblack** [comment]
Right now I'm leaning towards TypeScript, since it would allow dynamic imports with `require` (so users could write plugins for their own, unsupported repo clients), and I can also export types for the plugins to use.

But, just to give an example, I could use Yarn's zero-install feature. This means that dependencies actually get *tracked in the repo* instead of ignored ("zero-install" because once the repo's cloned it's ready for development, no install command required). Can't guarantee that I'll use that feature, since it bloats the repo's clone size, but I hope that's an example of how design choices can affect pre-install setup steps.

Another thing I'm curious about is if it would be helpful if I made a `Makefile`?

**Comment by 0323pin** [comment]
> Another thing I'm curious about is if it would be helpful if I made a Makefile?

Sure, why not. That would be nice.
Let me know when there's something in the pipeline.

**Comment by spenserblack** [comment]
Ref: #201 

@0323pin BTW, just want to let you know that it's OK if you don't want to support a language/toolchain you're not familiar with. Don't want to sound like you *have* to keep supporting the package, just that I'm happy to offer any help if I can :slightly_smiling_face:

**Comment by 0323pin** [comment]
@spenserblack yeah, I got that 😄 
No worries, let's have a look when the first version in TS comes out.

**Comment by spenserblack** [comment]
> first version in TS comes out.

Just an FYI I decided to use Ruby instead :slightly_smiling_face:
